version: 2.1

jobs:
  run-integration-tests:
    docker:
      - image: cimg/openjdk:17.0  # Contenedor base con Java 17
      - image: mysql:8.0          # Contenedor de MySQL
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: dbunit
    steps:
      - checkout  # Descarga el código fuente
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
      - run:
          name: Wait for MySQL to be Ready
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 3306 && echo "MySQL is up" && exit 0
              echo "Waiting for MySQL..."
              sleep 2
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Initialize Database
          command: |
            mysql -h 127.0.0.1 -P 3306 -u root -p123456 dbunit < src/test/resources/SQL_table.txt
      - run:
          name: Run Integration Test
          command: mvn test -Dtest=com.mayab.quality.integration.UserServiceTest
      - run:
          name: Notify
          command: echo "Integration Tests completed successfully."

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-integration-tests

    jobs:
      - run-integration-tests
