# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define jobs and workflows
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0  # Usa Java 17
    steps:
      - checkout  # Descarga el código fuente
      - run:
          name: Build Project
          command: mvn -B -DskipTests clean package  # Compila sin ejecutar pruebas
      - run:
          name: Notify
          command: echo "Tests completed successfully."

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
