version: 2.1

jobs:
  run-unit-tests:
    docker:
      - image: cimg/openjdk:17.0  # Imagen base con Java 17
    steps:
      - checkout  # Descarga el código fuente
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve  # Asegura que las dependencias estén disponibles
      - run:
          name: Run Unit Tests (UserServiceTest)
          command: mvn test -Dtest=com.mayab.quality.unittest.service.UserServiceTest -e -X
      - run:
          name: Notify
          command: echo "Unit Tests completed successfully."

  jobs:
  run-integration-tests:
    docker:
      - image: cimg/openjdk:17.0
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: dbunit
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client netcat
      - run:
          name: Test MySQL Connection
          command: |
            echo "Attempting to connect to MySQL..."
            for i in `seq 1 120`; do
              echo 'SELECT 1' | mysql -h 127.0.0.1 -P 3306 -u root -p123456 && echo "MySQL is ready!" && exit 0
              echo "Waiting for MySQL..."
              sleep 2
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Initialize Database
          command: |
            mysql -h 127.0.0.1 -P 3306 -u root -p123456 dbunit < src/test/resources/SQL_table.txt
      - run:
          name: Verify Tables in Database
          command: |
            mysql -h 127.0.0.1 -P 3306 -u root -p123456 -e "SHOW TABLES;" dbunit
      - run:
          name: Verify MySQL is Ready for Tests
          command: |
            mysql -h 127.0.0.1 -P 3306 -u root -p123456 -e "SELECT 1;"

      - run:
          name: Run Integration Test
          command: mvn test -Dtest=com.mayab.quality.integration.UserSeviceTest -e -X
      - run:
          name: Notify
          command: echo "Integration Tests completed successfully."


workflows:
  version: 2
  test-workflow:
    jobs:
      - run-unit-tests
      - run-integration-tests
